In [3]:
import cv2
import numpy as np

# Load the two images
image1 = cv2.imread('imag1.png')
image2 = cv2.imread('imag2.png')

# Ensure both images are the same size
if image1.shape != image2.shape:
    print("Error: Images must have the same dimensions.")
else:
    # Compute the absolute difference between the two images
    output_image = cv2.absdiff(image1, image2)
    print(output_image)

    # Display the output image
    cv2.imshow("Absolute Difference", output_image)

    # Wait until a key is pressed and close the windows
    cv2.waitKey(0)
    cv2.destroyAllWindows()


[[[ 19  45  66]
  [ 22  48  69]
  [ 23  52  72]
  ...
  [ 74  30   1]
  [ 76  32   1]
  [ 78  34   3]]

 [[ 20  46  68]
  [ 23  49  71]
  [ 23  52  73]
  ...
  [ 72  28   3]
  [ 74  30   1]
  [ 76  32   1]]

 [[ 20  46  68]
  [ 22  48  70]
  [ 24  53  74]
  ...
  [ 71  27   4]
  [ 72  28   3]
  [ 74  30   1]]

 ...

 [[165 150 126]
  [163 148 124]
  [161 146 124]
  ...
  [108  96  70]
  [111  99  73]
  [110  98  72]]

 [[157 142 118]
  [155 140 116]
  [153 138 116]
  ...
  [111  99  73]
  [113 101  75]
  [111  99  73]]

 [[146 131 107]
  [143 128 104]
  [141 126 104]
  ...
  [113 101  75]
  [116 104  78]
  [112 100  74]]]


In [4]:
import cv2
import numpy as np
from skimage.feature import hog
from skimage import exposure

# Load and preprocess the image to 64x128
image = cv2.imread('imag1.png', cv2.IMREAD_GRAYSCALE)
image = cv2.resize(image, (64, 128))

# Step 2: Calculate Gradients (x and y directions)
gradient_x = cv2.Sobel(image, cv2.CV_64F, 1, 0, ksize=1)
gradient_y = cv2.Sobel(image, cv2.CV_64F, 0, 1, ksize=1)

# Step 3: Calculate the Magnitude and Orientation
magnitude = np.sqrt(gradient_x**2 + gradient_y**2)
orientation = np.arctan2(gradient_y, gradient_x) * (180 / np.pi) % 180  # Converting to degrees in [0, 180]

# Step 4 & 5: Calculate Histogram of Gradients in 8×8 cells and normalize in 16×16 cells
# Define HOG parameters
cell_size = (8, 8)    # Each cell is 8x8 pixels
block_size = (2, 2)   # Each block contains 2x2 cells (16x16 pixels)
nbins = 9             # Number of orientation bins

# Compute HOG features
hog_features, hog_image = hog(image,
                              orientations=nbins,
                              pixels_per_cell=cell_size,
                              cells_per_block=block_size,
                              block_norm='L2-Hys',
                              visualize=True,
                              transform_sqrt=True)

print(hog_features)

# Step 6: Display HOG features for the complete image
hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 10))

# Show original and HOG images
cv2.imshow("Original Image", image)
cv2.imshow("HOG Features", hog_image_rescaled)
cv2.waitKey(0)
cv2.destroyAllWindows()


[0.58752516 0.00343832 0.         ... 0.         0.01244641 0.14471686]
